[package]
name = "trufc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.20", features = ["derive"] }
once_cell = "1.20.2"
serde = { version = "1.0.214", features = ["derive"] }
toml = "0.8.19"
